#!/usr/bin/env python3


import pandas as pd
import os
import sys 

os.system('curl -s -O https://www.fca.org.uk/publication/data/short-positions-daily-update.xls')
df = pd.read_excel('./short-positions-daily-update.xls', sheet_name=0)
os.system('rm ./short-positions-daily-update.xls')
#df = pd.read_excel('http://www.fca.org.uk/publication/data/short-positions-daily-update.xls', sheet_name=0)
df.to_csv(sys.stdout, index=False, sep='|')
#print(df)
