#!/usr/bin/env python3

import pandas as pd
import os
import sys

# read the stockchallenge ftse data
dfs = pd.read_html('http://www.stockchallenge.co.uk/ftse.php', header=0)
# the first big table is the one we want
df = dfs[0]
df = df[[ 'EPIC','Mkt cap (m)*']]
df.to_csv(sys.stdout, index=False, header=False, sep=' ')

